# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Scribble App Prod

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: git fetch origin $GITHUB_REF:$GITHUB_REF -u
      - run: git checkout $GITHUB_REF -f
      - run: git pull origin $GITHUB_REF
      - run: npm ci
      - run: npm run build
      - run: rsync -a --no-perms --no-times --checksum --delete -v --chown=www-data:www-data ./dist/ ${{ secrets.WEB_ROOT_PATH }}
